name: '5 min deploy'

on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  auto-deploy-trigger:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'master'
        development_branch: 'production'
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
